import os

from dotenv import load_dotenv

load_dotenv()

JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
JWT_ACCESS_TOKEN_SECRET = os.getenv("JWT_ACCESS_TOKEN_SECRET")
JWT_REFRESH_TOKEN_SECRET = os.getenv("JWT_REFRESH_TOKEN_SECRET")
ACCESS_TOKEN_COOKIE_NAME = os.getenv("ACCESS_TOKEN_COOKIE_NAME")
REFRESH_TOKEN_COOKIE_NAME = os.getenv("REFRESH_TOKEN_COOKIE_NAME")
JWT_ACCESS_TOKEN_EXPIRES = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
JWT_REFRESH_TOKEN_EXPIRES = os.getenv("JWT_REFRESH_TOKEN_EXPIRES")

ENV = {
    "JWT_ALGORITHM": JWT_ALGORITHM,
    "JWT_ACCESS_TOKEN_SECRET": JWT_ACCESS_TOKEN_SECRET,
    "JWT_REFRESH_TOKEN_SECRET": JWT_REFRESH_TOKEN_SECRET,
    "ACCESS_TOKEN_COOKIE_NAME": ACCESS_TOKEN_COOKIE_NAME,
    "REFRESH_TOKEN_COOKIE_NAME": REFRESH_TOKEN_COOKIE_NAME,
    "JWT_ACCESS_TOKEN_EXPIRES": JWT_ACCESS_TOKEN_EXPIRES,
    "JWT_REFRESH_TOKEN_EXPIRES": JWT_REFRESH_TOKEN_EXPIRES,
}
