import os

from dotenv import load_dotenv

load_dotenv()

JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
JWT_ACCESS_TOKEN_SECRET = os.getenv("JWT_ACCESS_TOKEN_SECRET")
JWT_REFRESH_TOKEN_SECRET = os.getenv("JWT_REFRESH_TOKEN_SECRET")
ACCESS_TOKEN_COOKIE_NAME = os.getenv("ACCESS_TOKEN_COOKIE_NAME")
REFRESH_TOKEN_COOKIE_NAME = os.getenv("REFRESH_TOKEN_COOKIE_NAME")
JWT_ACCESS_TOKEN_EXPIRES = os.getenv("JWT_ACCESS_TOKEN_EXPIRES")
JWT_REFRESH_TOKEN_EXPIRES = os.getenv("JWT_REFRESH_TOKEN_EXPIRES")

# 결제 대기(PENDING) 상태로 이 시간(분)만큼 방치된 주문은 자동으로 취소되고 재고가 복구됩니다.
ORDER_PENDING_EXPIRATION_MINUTES = int(os.getenv("ORDER_PENDING_EXPIRATION_MINUTES", "30"))

ENV = {
    "JWT_ALGORITHM": JWT_ALGORITHM,
    "JWT_ACCESS_TOKEN_SECRET": JWT_ACCESS_TOKEN_SECRET,
    "JWT_REFRESH_TOKEN_SECRET": JWT_REFRESH_TOKEN_SECRET,
    "ACCESS_TOKEN_COOKIE_NAME": ACCESS_TOKEN_COOKIE_NAME,
    "REFRESH_TOKEN_COOKIE_NAME": REFRESH_TOKEN_COOKIE_NAME,
    "JWT_ACCESS_TOKEN_EXPIRES": JWT_ACCESS_TOKEN_EXPIRES,
    "JWT_REFRESH_TOKEN_EXPIRES": JWT_REFRESH_TOKEN_EXPIRES,
    "ORDER_PENDING_EXPIRATION_MINUTES": ORDER_PENDING_EXPIRATION_MINUTES,
}
