import { PRODUCT_IMAGES } from "./product-images";

// TRNDY 전체 상품 카탈로그 (홈페이지 / 상품 목록 / 상품 상세가 전부 이 데이터를 공유합니다)
//
// category: 홈페이지 상단 탭(ALL PRODUCTS/NEW/DENIM/KNIT/BAG & SHOES)에서 사용하는 분류
// shopCategory: 상품 목록 페이지 필터 칩(전체/상의/하의/아우터/잡화)에서 사용하는 분류
export interface Product {
  id: number;
  name: string;
  price: number;
  category: "NEW" | "DENIM" | "BAG" | "SHOES" | "KNIT" | "BOTTOM" | "OUTER" | "TOP";
  shopCategory: "상의" | "하의" | "아우터" | "잡화";
  image: string;
  isSale: boolean;
  discount: number;
  tag: string;
  desc: string;
  color: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "시그니처 오버핏 코튼 셔츠",
    price: 59000,
    category: "NEW",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.shirt,
    isSale: true,
    discount: 15,
    tag: "BEST",
    desc: "이집트산 프리미엄 코튼 100%로 짜여진 유려한 피팅감",
    color: "화이트",
  },
  {
    id: 2,
    name: "클래식 와이드 데님 팬츠",
    price: 78000,
    category: "DENIM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.denim,
    isSale: false,
    discount: 0,
    tag: "ESSENTIAL",
    desc: "14온스 링방적 하이엔드 셀비지 데님 라인",
    color: "인디고",
  },
  {
    id: 3,
    name: "미니멀 레더 바디 백팩",
    price: 145000,
    category: "BAG",
    shopCategory: "잡화",
    image: PRODUCT_IMAGES.bag,
    isSale: false,
    discount: 0,
    tag: "MD PICK",
    desc: "이탈리아 풀그레인 레더를 가공한 시크한 실루엣",
    color: "브라운",
  },
  {
    id: 4,
    name: "어반 스웨이드 스니커즈",
    price: 112000,
    category: "SHOES",
    shopCategory: "잡화",
    image: PRODUCT_IMAGES.sneakers,
    isSale: true,
    discount: 20,
    tag: "LOW STOCK",
    desc: "천연 화강암 스웨이드 텍스처와 인체공학 아웃솔",
    color: "그레이",
  },
  {
    id: 5,
    name: "파인 울 라운드 니트 웨어",
    price: 89000,
    category: "KNIT",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.knit,
    isSale: true,
    discount: 10,
    tag: "NEW",
    desc: "메리노 울 본연의 보온성과 구름 같은 원사 마감",
    color: "네이비",
  },
  {
    id: 6,
    name: "워시드 카펜터 나일론 팬츠",
    price: 69000,
    category: "BOTTOM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.casualPants,
    isSale: false,
    discount: 0,
    tag: "TREND",
    desc: "밀리터리 테크웨어에서 영감을 얻은 고밀도 나일론",
    color: "카키",
  },
  {
    id: 7,
    name: "모던 실루엣 투버튼 재킷",
    price: 189000,
    category: "OUTER",
    shopCategory: "아우터",
    image: PRODUCT_IMAGES.jacket,
    isSale: false,
    discount: 0,
    tag: "PRE-ORDER",
    desc: "어깨선부터 툭 떨어지는 입체적 3D 테일러드 공정",
    color: "블랙",
  },
  {
    id: 8,
    name: "스테디 크루넥 스웨트셔츠",
    price: 45000,
    category: "TOP",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.sweatshirt,
    isSale: true,
    discount: 30,
    tag: "SEASON OFF",
    desc: "중량감 있는 헤비웨이트 프렌치 테리 코튼 원단",
    color: "멜란지그레이",
  },
  {
    id: 9,
    name: "실크 블렌드 시어 블라우스",
    price: 95000,
    category: "NEW",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.blouse,
    isSale: false,
    discount: 0,
    tag: "ELEGANT",
    desc: "은은한 내추럴 광택감이 감도는 시스루 포멀 텍스처",
    color: "아이보리",
  },
  {
    id: 10,
    name: "어반 테이퍼드 치노 슬랙스",
    price: 62000,
    category: "BOTTOM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.slacks,
    isSale: true,
    discount: 15,
    tag: "STEADY",
    desc: "링클프리 코팅 가공으로 하루 종일 칼핏 유지",
    color: "베이지",
  },
  {
    id: 11,
    name: "비건 레더 미니멀 보스턴백",
    price: 168000,
    category: "BAG",
    shopCategory: "잡화",
    image: PRODUCT_IMAGES.bostonBag,
    isSale: false,
    discount: 0,
    tag: "HIGH-END",
    desc: "스크래치에 강한 프리미엄 친환경 마이크로파이버 가죽",
    color: "블랙",
  },
  {
    id: 12,
    name: "모노크롬 가디건 크롭 베스트",
    price: 53000,
    category: "KNIT",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.cardigan,
    isSale: true,
    discount: 25,
    tag: "LAST PIECE",
    desc: "유니크한 비대칭 클로징 단추 포인트 레이어드 아이템",
    color: "차콜",
  },
  {
    id: 13,
    name: "린넨 오버사이즈 셔츠",
    price: 45000,
    category: "TOP",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.shirt,
    isSale: false,
    discount: 0,
    tag: "NEW",
    desc: "가볍게 걸치기 좋은 내추럴 텍스처의 린넨 혼방 셔츠",
    color: "베이지",
  },
  {
    id: 14,
    name: "와이드 버뮤다 팬츠",
    price: 52000,
    category: "BOTTOM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.casualPants,
    isSale: false,
    discount: 0,
    tag: "BEST",
    desc: "여유 있는 와이드 핏으로 편안하게 즐기는 여름 팬츠",
    color: "블랙",
  },
  {
    id: 15,
    name: "미니멀 크로스 레더백",
    price: 128000,
    category: "BAG",
    shopCategory: "잡화",
    image: PRODUCT_IMAGES.bag,
    isSale: false,
    discount: 0,
    tag: "",
    desc: "가볍게 크로스로 매치하기 좋은 미니멀 레더 크로스백",
    color: "브라운",
  },
  {
    id: 16,
    name: "실버 버클 가죽 샌들",
    price: 69000,
    category: "SHOES",
    shopCategory: "잡화",
    image: PRODUCT_IMAGES.sneakers,
    isSale: true,
    discount: 15,
    tag: "SALE",
    desc: "실버 버클 포인트가 돋보이는 시즌 레더 샌들",
    color: "실버",
  },
  {
    id: 17,
    name: "소프트 세미와이드 데님",
    price: 49000,
    category: "DENIM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.denim,
    isSale: false,
    discount: 0,
    tag: "BEST",
    desc: "부드러운 워싱감의 세미와이드 데님 팬츠",
    color: "연청",
  },
  {
    id: 18,
    name: "카고 포켓 롱 스커트",
    price: 42000,
    category: "BOTTOM",
    shopCategory: "하의",
    image: PRODUCT_IMAGES.slacks,
    isSale: false,
    discount: 0,
    tag: "",
    desc: "카고 포켓 디테일이 포인트인 유틸리티 롱 스커트",
    color: "카키",
  },
  {
    id: 19,
    name: "스퀘어넥 슬리브리스 티",
    price: 24000,
    category: "TOP",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.blouse,
    isSale: false,
    discount: 0,
    tag: "",
    desc: "레이어드하기 좋은 스퀘어넥 슬리브리스 이너 티",
    color: "화이트",
  },
  {
    id: 20,
    name: "스트라이프 하프 니트",
    price: 38000,
    category: "KNIT",
    shopCategory: "상의",
    image: PRODUCT_IMAGES.knit,
    isSale: true,
    discount: 15,
    tag: "SALE",
    desc: "산뜻한 스트라이프 패턴의 하프 슬리브 니트",
    color: "네이비",
  },
];

export function getProductById(id: number): Product | undefined {
  return PRODUCTS.find((product) => product.id === id);
}
